kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  clusterIP: None
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: centos
spec:
  selector:
    matchLabels:
      app: centos
  serviceName: centos
  replicas: 1
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centos
        image: centos:8
 